src/Rondinelli.MyHouseFinance.UI.MVC/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rondinelli.MyHouseFinance.Application.Interfaces;
using Rondinelli.MyHouseFinance.Application.ViewModels;
using Rondinelli.MyHouseFinance.Util.Enum;

namespace Rondinelli.MyHouseFinance.UI.MVC.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly IRelatorioAppService _relatorioAppService;
        public RelatorioController(IRelatorioAppService relatorioAppService)
        {
            _relatorioAppService = relatorioAppService;
        }
        public void CarregarCombobox()
        {
            ViewBag.TipoPagamentoLista = EnumTipoPagamento.GetList();
            ViewBag.ResponsavelLista = UsuarioViewModel.ListarTodos();
            ViewBag.CategoriaLista = CategoriaViewModel.ListarTodos();
        }
        // GET: Relatorio
        public ActionResult Index()
        {
            CarregarCombobox();
            return View();
        }

        public JsonResult GraficoPorDespesas(string mesReferencia)
        {
            var lista = _relatorioAppService.GerarGraficoPorDespesas(mesReferencia);

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GraficoPagamento(string mesReferencia, string usuarioId)
        {
            var lista = _relatorioAppService.GerarGraficoPagamento(mesReferencia, usuarioId);

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GraficoDoResponsavel(string mesReferencia, string usuarioId)
        {
            var lista = _relatorioAppService.GraficoDoResponsavel(mesReferencia, usuarioId);

            return Json(lista, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Relatorio/Index.cshtml
@{

    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

<h2>Relatórios</h2>
<div class="form-group">
    <div class="row">
        <div class="col-sm-1">
            Categoria:
        </div>
        <div class="col-sm-2">
            @Html.DropDownList("Nome", new SelectList(ViewBag.CategoriaLista, "Id", "Nome"), "Selecione", new { @class = "form-control" })
        </div>
        <div class="col-sm-1">
            Responsável:
        </div>
        <div class="col-sm-2">
            @Html.DropDownList("responsavelId", new SelectList(ViewBag.ResponsavelLista, "Id", "Nome"), "Selecione", new { @class = "form-control" })
        </div>
        <div class="col-sm-1">
            Mês Referência:
        </div>
        <div class="col-sm-2">
            <input type="text" class="form-control dataMesPicker" name="mesReferenciaz" id="mesReferencia" maxlength="40">
        </div>
    </div>
    <div class="row">
        <br/>     
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <input type="button" value="Relatório Categorias" class="btn btn-success" onclick="gerarGrafico()" />
    </div>
    <div class="col-md-2">
        <input type="button" value="Resumo Pagamento" class="btn btn-success" onclick="gerarGraficoPagamento()" />
    </div>
    <div class="col-md-2">
        <input type="button" value="Despesa por Pessoa" class="btn btn-success" onclick="gerarGraficoPagamentoPorPessoa()" />
    </div>
</div>

@Html.Hidden("IdUrlDoResponsavel", Url.Action("GraficoDoResponsavel", "Relatorio"))
@Html.Hidden("IdUrlPorPagamento", Url.Action("GraficoPagamento", "Relatorio"))
@Html.Hidden("IdUrlPorDespesa", Url.Action("GraficoPorDespesas", "Relatorio"))

<canvas id="myChart" width="100" height="100"></canvas>

@section scripts
{
    @Scripts.Render("~/bundles/datetimepicker")
    @Scripts.Render("~/bundles/relatorio")
}

@section css
{
    @Styles.Render("~/Content/datetimepickercss")
}