src/Rondinelli.MyHouseFinance.UI.MVC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rondinelli.MyHouseFinance.Application.Interfaces;
using Rondinelli.MyHouseFinance.Application.ViewModels;
using Rondinelli.MyHouseFinance.Util.Enum;

namespace Rondinelli.MyHouseFinance.UI.MVC.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioAppService _usuarioAppService;
        public UsuarioController(IUsuarioAppService usuarioAppService)
        {
            _usuarioAppService = usuarioAppService;
        }
        public void CarregarCombobox()
        {
            ViewBag.CategoriaPessoaLista = EnumCategoriaPessoa.GetList();
        }

        // GET: Usuario
        public ActionResult Index()
        {
            return View(_usuarioAppService.ObterTodos().ToList());
        }

        public ActionResult Criar()
        {
            CarregarCombobox();

            return View(new UsuarioViewModel());
        }

        [HttpPost]
        public ActionResult Criar(UsuarioViewModel usuario)
        {
            try
            {
                CarregarCombobox();
                if (ModelState.IsValid)
                {                    
                    _usuarioAppService.Adicionar(usuario);
                    TempData["sucesso"] = EnumMensagem.SALVO.Description;
                }
                else
                {
                    TempData["erro"] = String.Join(";", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                    return View(usuario);
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["erro"] = e.Message;
                return View(usuario);
            }
        }

        public ActionResult Editar(Guid id)
        {
            CarregarCombobox();
            var usuario = _usuarioAppService.ObterPorId(id);
            if (usuario != null)
            {
                return View(usuario);
            }
            else
            {
                TempData["erro"] = EnumMensagem.NOT_FOUND.Description;
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        public ActionResult Editar(UsuarioViewModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    usuario = _usuarioAppService.Atualizar(usuario);
                    TempData["sucesso"] = EnumMensagem.EDITADO.Description;
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["erro"] = String.Join(";", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                    return View(usuario);
                }
            }
            catch (Exception e)
            {
                TempData["erro"] = e.Message;
                return View(usuario);
            }
        }

        public ActionResult Deletar(Guid id)
        {
            try
            {
                _usuarioAppService.Deletar(id);
                TempData["sucesso"] = EnumMensagem.DELETADO.Description;
            }
            catch (Exception e)
            {
                TempData["erro"] = e.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Usuario/Criar.cshtml
@model Rondinelli.MyHouseFinance.Application.ViewModels.UsuarioViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UsuarioViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaPessoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoriaPessoa, new SelectList(ViewBag.CategoriaPessoaLista, "Value", "Description"), "Selecione...", new { @id = "ddlCategoriaPessoaId", @class = "dropdown-toggle form-control comboboxS2" })
                @Html.ValidationMessageFor(model => model.CategoriaPessoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Usuario/Editar.cshtml
@model Rondinelli.MyHouseFinance.Application.ViewModels.UsuarioViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UsuarioViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaPessoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoriaPessoa, new SelectList(ViewBag.CategoriaPessoaLista, "Value", "Description"), "Selecione...", new { @id = "ddlCategoriaPessoaId", @class = "dropdown-toggle form-control comboboxS2" })
                @Html.ValidationMessageFor(model => model.CategoriaPessoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Usuario/Index.cshtml
@model IEnumerable<Rondinelli.MyHouseFinance.Application.ViewModels.UsuarioViewModel>

<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts
{
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
    </script>
}

<p>
    <div class="form-group">
        <div class="col-md-10">
            <input type="button" value="Criar" class="btn btn-primary" onclick="location.href='@Url.Action("Criar", "Usuario")'" />
        </div>
    </div>
    <br />
</p>
<table id="tableUsuario" class="display" style="width: 100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriaPessoa)
            </th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoriaPessoa)
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" value="Editar" class="btn btn-success" onclick="location.href = '@Url.Action("Editar", "Usuario", new {id = item.Id})'" />
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" value="Deletar" class="btn btn-danger" onclick="location.href = '@Url.Action("Deletar", "Usuario", new {id = item.Id})'" />
                        </div>
                    </div>
                </td>
            </tr>
        }

    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        $('#tableUsuario').DataTable(
            {
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"
                }
            });
    });
</script>