src/Rondinelli.MyHouseFinance.UI.MVC/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rondinelli.MyHouseFinance.Application.Interfaces;
using Rondinelli.MyHouseFinance.Application.ViewModels;
using Rondinelli.MyHouseFinance.Util.Enum;

namespace Rondinelli.MyHouseFinance.UI.MVC.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICategoriaAppService _categoriaAppService;

        public CategoriaController(ICategoriaAppService categoriaAppService)
        {
            _categoriaAppService = categoriaAppService;
        }
        
        public ActionResult Index()
        {
            return View(_categoriaAppService.ObterTodos().ToList());
        }

        public ActionResult Criar()
        {            
            return View(new CategoriaViewModel());
        }

        [HttpPost]
        public ActionResult Criar(CategoriaViewModel categoria)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _categoriaAppService.Adicionar(categoria);
                    TempData["sucesso"] = EnumMensagem.SALVO.Description;                    
                }
                else
                {
                    TempData["erro"] = String.Join(";", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                    return View(categoria);
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["erro"] = e.Message;
                return View(categoria);
            }
        }


        public ActionResult Editar(Guid id)
        {            
            var categoria = _categoriaAppService.ObterPorId(id);
            if (categoria != null)
            {
                return View(categoria);
            }
            else
            {
                TempData["erro"] = EnumMensagem.NOT_FOUND.Description;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Editar(CategoriaViewModel categoria)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    categoria = _categoriaAppService.Atualizar(categoria);
                    TempData["sucesso"] = EnumMensagem.EDITADO.Description;
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["erro"] = String.Join(";", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                    return View(categoria);
                }
            }
            catch (Exception e)
            {
                TempData["erro"] = e.Message;
                return View(categoria);
            }
        }

        public ActionResult Deletar(Guid id)
        {
            try
            {
                //Implementar o validar exclusão

                _categoriaAppService.Deletar(id);
                TempData["sucesso"] = EnumMensagem.DELETADO.Description;

            }
            catch (Exception e)
            {
                TempData["erro"] = e.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Categoria/Criar.cshtml
@model Rondinelli.MyHouseFinance.Application.ViewModels.CategoriaViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoriaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Categoria/Editar.cshtml
@model Rondinelli.MyHouseFinance.Application.ViewModels.CategoriaViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoriaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Categoria/Index.cshtml
@model IEnumerable<Rondinelli.MyHouseFinance.Application.ViewModels.CategoriaViewModel>


<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts
{
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
    </script>
}


<p>
    <div class="form-group">
        <div class="col-md-10">
            <input type="button" value="Criar" class="btn btn-primary" onclick="location.href='@Url.Action("Criar", "Categoria")'" />
        </div>
    </div>
    <br />
</p>
<table id="tableCategoria" class="display" style="width: 100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" value="Editar" class="btn btn-success" onclick="location.href = '@Url.Action("Editar", "Categoria", new {id = item.Id})'" />
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" value="Deletar" class="btn btn-danger" onclick="location.href = '@Url.Action("Deletar", "Categoria", new {id = item.Id})'" />
                        </div>
                    </div>
                </td>
            </tr>
        }

    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        $('#tableCategoria').DataTable(
            {
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"
                }
            });
    });
</script>