src/Rondinelli.MyHouseFinance.UI.MVC/Controllers/DespesaController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rondinelli.MyHouseFinance.Application.Interfaces;
using Rondinelli.MyHouseFinance.Application.ViewModels;
using Rondinelli.MyHouseFinance.Util.Enum;

namespace Rondinelli.MyHouseFinance.UI.MVC.Controllers
{
    public class DespesaController : Controller
    {
        private readonly IDespesaAppService _despesaAppService;

        public DespesaController(IDespesaAppService despesaAppService)
        {
            _despesaAppService = despesaAppService;
        }

        public void CarregarCombobox()
        {
            ViewBag.TipoPagamentoLista = EnumTipoPagamento.GetList();
            ViewBag.ResponsavelLista = UsuarioViewModel.ListarTodos();
            ViewBag.CategoriaLista = CategoriaViewModel.ListarTodos();
            ViewBag.ResposavelListaMulti = new MultiSelectList(UsuarioViewModel.ListarTodos(), "Id", "Nome");
        }

        // GET: Despesa
        public ActionResult Index()
        {
            var todos = _despesaAppService.ObterTodos().ToList();
            return View(todos);
        }       

        public ActionResult Criar()
        {
            CarregarCombobox();
            return View(new DespesaViewModel());
        }

        [HttpPost]
        public ActionResult Criar(DespesaViewModel despesa)
        {
            try
            {                
                if (ModelState.IsValid)
                {                   
                    _despesaAppService.Adicionar(despesa);
                    TempData["sucesso"] = EnumMensagem.SALVO.Description;                                        
                }
                else
                {
                    CarregarCombobox();
                    TempData["erro"] = String.Join(";", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                    return View(despesa);
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                CarregarCombobox();
                TempData["erro"] = e.Message;
                return View(despesa);
            }
        }

        public ActionResult Editar(Guid id)
        {
            CarregarCombobox();
            var despesa = _despesaAppService.ObterPorId(id);
            if (despesa != null)
            {
                return View(despesa);
            }
            else
            {
                TempData["erro"] = EnumMensagem.NOT_FOUND.Description;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Editar(DespesaViewModel despesa)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    despesa = _despesaAppService.Atualizar(despesa);
                    TempData["sucesso"] = EnumMensagem.EDITADO.Description;
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["erro"] = String.Join(";", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                    return View(despesa);
                }
            }
            catch (Exception e)
            {
                CarregarCombobox();
                TempData["erro"] = e.Message;
                return View(despesa);
            }
        }

        public ActionResult Deletar(Guid id)
        {
            try
            {
                //Implementar o validar exclusão

                _despesaAppService.Deletar(id);
                TempData["sucesso"] = EnumMensagem.DELETADO.Description;

            }
            catch (Exception e)
            {
                TempData["erro"] = e.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Despesa/Criar.cshtml
@model Rondinelli.MyHouseFinance.Application.ViewModels.DespesaViewModel


@section scripts
{
    @Scripts.Render("~/bundles/datetimepicker")
}

@section css
{
    @Styles.Render("~/Content/datetimepickercss")
}

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Despesa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoriaId, new SelectList(ViewBag.CategoriaLista, "Id", "Nome"), "Selecione...", new { @id = "ddlCategoriaListaId", @class = "dropdown-toggle form-control comboboxS2" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MesReferencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MesReferencia, new { htmlAttributes = new { @class = "form-control dataMesPicker" } })
                @Html.ValidationMessageFor(model => model.MesReferencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control money2" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCompra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCompra, new { htmlAttributes = new { @class = "form-control dataPickerMask dataTPicker" } })
                @Html.ValidationMessageFor(model => model.DataCompra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parcelas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parcelas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Parcelas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoPagamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.TipoPagamento, new SelectList(ViewBag.TipoPagamentoLista, "Value", "Description"), "Selecione...", new { @id = "ddlTipoPagamentoListaId", @class = "dropdown-toggle form-control comboboxS2" })
                @Html.ValidationMessageFor(model => model.TipoPagamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Casal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Casal, htmlAttributes: new { @checked = true, @id = "EhCasal" })
                    @Html.ValidationMessageFor(model => model.Casal, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DividirDespesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.DividirDespesa, htmlAttributes: new { @checked = true, @id = "EhDivisao" })
                    @Html.ValidationMessageFor(model => model.DividirDespesa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group usuarioCombo">
            @Html.LabelFor(model => model.ResponsavelPagadorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ResponsavelPagadorId, new SelectList(ViewBag.ResponsavelLista, "Id", "Nome"), "Selecione...", new { @id = "ddlResponsavelListaId", @class = "dropdown-toggle form-control comboboxS2" })
                @Html.ValidationMessageFor(model => model.ResponsavelPagador, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group usuariosCombo">
            @Html.LabelFor(model => model.ResponsavelPagadorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Ids", (MultiSelectList)ViewBag.ResposavelListaMulti, new { multiple = "multiple",
               @class = "dropdown-toggle form-control multiple2" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-1">
                <input type="button" value="Voltar" class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Despesa")'" />
            </div>
            <div class="col-md-1">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        HabilitarPagador();
        HabilitarPagadores();
    });
</script>

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Despesa/Editar.cshtml
@model Rondinelli.MyHouseFinance.Application.ViewModels.DespesaViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DespesaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MesReferencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MesReferencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MesReferencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.DataCompra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCompra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCompra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parcelas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parcelas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Parcelas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoPagamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.TipoPagamento, new SelectList(ViewBag.TipoPagamentoLista, "Value", "Description"), "Selecione...", new { @id = "ddlTipoPagamentoListaId", @class = "dropdown-toggle form-control comboboxS2" })
                @Html.ValidationMessageFor(model => model.TipoPagamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Casal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Casal, htmlAttributes: new { @checked = true, @id = "EhCasal" })
                    @Html.ValidationMessageFor(model => model.Casal, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <div class="form-group usuarioCombo">
            @Html.LabelFor(model => model.ResponsavelPagadorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ResponsavelPagadorId, new SelectList(ViewBag.ResponsavelLista, "Id", "Nome"), "Selecione...", new { @id = "ddlResponsavelListaId", @class = "dropdown-toggle form-control comboboxS2" })
                @Html.ValidationMessageFor(model => model.ResponsavelPagador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    $(document).ready(function () {
        HabilitarPagador();

    });
</script>

src/Rondinelli.MyHouseFinance.UI.MVC/Views/Despesa/Index.cshtml
@model IEnumerable<Rondinelli.MyHouseFinance.Application.ViewModels.DespesaViewModel>

<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts
{
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
    </script>
}



<p>
    <div class="form-group">
        <div class="col-md-10">
            <input type="button" value="Criar" class="btn btn-primary" onclick="location.href='@Url.Action("Criar", "Despesa")'" />
        </div>
    </div>
    <br />
</p>
<br />
<table id="tableDespesa" class="display" style="width: 100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MesReferencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCompra)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parcelas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoPagamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResponsavelPagadorId)
            </th>

            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MesReferencia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataCompra)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Parcelas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoPagamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ResponsavelPagador.Nome)
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" value="Editar" class="btn btn-success" onclick="location.href = '@Url.Action("Editar", "Despesa", new {id = item.Id})'" />
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" value="Deletar" class="btn btn-danger" onclick="location.href = '@Url.Action("Deletar", "Despesa", new {id = item.Id})'" />
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tableDespesa').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"                    
            }
        });
    });
</script>